# Shinken reactioner with only reactioner role
#
FROM        shinken-base
MAINTAINER  Manuel Villarejo <mjvillarejo@gmail.com>

ADD         files/shinken-reactionner.conf /etc/supervisord.d/

EXPOSE      7769
