# Shinken receiver with only receiver role
FROM        shinken-base
MAINTAINER  Manuel Villarejo <mjvillarejo@gmail.com>

ADD         files/shinken-receiver.conf /etc/supervisord.d/

EXPOSE      7773
