# Shinken broker with only broker role
#
FROM        shinken-base
MAINTAINER  Manuel Villarejo <mjvillarejo@gmail.com>

ADD         files/shinken-broker.conf /etc/supervisord.d/

EXPOSE      7772
EXPOSE      50000
EXPOSE      7767
